In [ ]:
!pip install vecstack

from vecstack import stacking
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score as acc
from sklearn.metrics import r2_score as r2

pd.options.display.max_rows = 300
pd.options.display.max_columns = 100

import warnings
warnings.filterwarnings("ignore")


from google.colab import drive
drive.mount('/gdrive')
#Change current working directory to gdrive
%cd /gdrive



Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).
/gdrive


In [ ]:
trainfile = r'/gdrive/My Drive/ColabNotebooks/Team Assignment/few_missing_hotcoded_train.csv'
trainData = pd.read_csv(trainfile) #creates a dataframe
testfile = r'/gdrive/My Drive/ColabNotebooks/Team Assignment/few_missing_hotcoded_test.csv'
testData = pd.read_csv(testfile)  #creates a dataframe


print(trainData.shape)
print(testData.shape)

(1460, 271)
(1459, 270)


In [ ]:
#Extract training and test data
y_train = trainData["SalePrice"]
X_train = trainData.drop(["SalePrice"], axis=1) #extracting training data without the target column

#We don't have target columns this time
#y_test = testData["SalePrice"] 
X_test = testData #extracting training data without the first columns

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
X_train.head()

(1460, 270)
(1459, 270)
(1460,)


Id  MSSubClass  LotArea  OverallQual  OverallCond  YearBuilt  YearRemodAdd  \
0   1          60     8450            7            5       2003          2003   
1   2          20     9600            6            8       1976          1976   
2   3          60    11250            7            5       2001          2002   
3   4          70     9550            7            5       1915          1970   
4   5          60    14260            8            5       2000          2000   

   MasVnrArea  BsmtFinSF1  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF  1stFlrSF  \
0       196.0       706.0         0.0      150.0        856.0       856   
1         0.0       978.0         0.0      284.0       1262.0      1262   
2       162.0       486.0         0.0      434.0        920.0       920   
3         0.0       216.0         0.0      540.0        756.0       961   
4       350.0       655.0         0.0      490.0       1145.0      1145   

   2ndFlrSF  LowQualFinSF  GrLivArea  BsmtFullBath  BsmtHalfBath  FullBath  \
0       854             0       1710           1.0           0.0         2   
1         0             0       1262           0.0           1.0         2   
2       866             0       1786           1.0           0.0         2   
3       756             0       1717           1.0           0.0         1   
4      1053             0       2198           1.0           0.0         2   

   HalfBath  BedroomAbvGr  KitchenAbvGr  TotRmsAbvGrd  Fireplaces  \
0         1             3             1             8           0   
1         0             3             1             6           1   
2         1             3             1             6           1   
3         0             3             1             7           1   
4         1             4             1             9           1   

   GarageYrBlt  GarageCars  GarageArea  WoodDeckSF  OpenPorchSF  \
0       2003.0         2.0       548.0           0           61   
1       1976.0         2.0       460.0         298            0   
2       2001.0         2.0       608.0           0           42   
3       1998.0         3.0       642.0           0           35   
4       2000.0         3.0       836.0         192           84   

   EnclosedPorch  3SsnPorch  ScreenPorch  PoolArea  MiscVal  MoSold  YrSold  \
0              0          0            0         0        0       2    2008   
1              0          0            0         0        0       5    2007   
2              0          0            0         0        0       9    2008   
3            272          0            0         0        0       2    2006   
4              0          0            0         0        0      12    2008   

   MSZoning_C (all)  MSZoning_FV  MSZoning_RH  MSZoning_RL  MSZoning_RM  \
0                 0            0            0            1            0   
1                 0            0            0            1            0   
2                 0            0            0            1            0   
3                 0            0            0            1            0   
4                 0            0            0            1            0   

   Street_Grvl  Street_Pave  LotShape_IR1  LotShape_IR2  LotShape_IR3  \
0            0            1             0             0             0   
1            0            1             0             0             0   
2            0            1             1             0             0   
3            0            1             1             0             0   
4            0            1             1             0             0   

   LotShape_Reg  LandContour_Bnk  LandContour_HLS  LandContour_Low  ...  \
0             1                0                0                0  ...   
1             1                0                0                0  ...   
2             0                0                0                0  ...   
3             0                0                0                0  ...   
4             0                0      

In [ ]:
#Defining parameters
import math
#Setting a DTR model
model = DecisionTreeRegressor()
x = X_train
y = y_train
test = X_test

#Put in the function for prediction and outputs
model.fit(x,y)
rmse = math.sqrt(mean_squared_error(y, model.predict(x)))
print(rmse)
cross_val_score(model,x,y,cv=3, scoring="neg_mean_squared_error")


0.0


array([-1.55980917e+09, -1.66416252e+09, -3.19721651e+09])

In [ ]:
#Check the shape of the tree
print(model.get_depth())
print(model.get_n_leaves())
print(model.get_params())

30
1399
{'criterion': 'mse', 'max_depth': None, 'max_features': None, 'max_leaf_nodes': None, 'min_impurity_decrease': 0.0, 'min_impurity_split': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'presort': False, 'random_state': None, 'splitter': 'best'}


In [ ]:
#Save predictions
output_directory = r'/gdrive/My Drive/ColabNotebooks/Team Assignment/DT_Reg.csv'
predictions = model.predict(test)
ID = test["Id"]
predict=pd.DataFrame(predictions,columns=['SalePrice'])
pd.concat([ID, predict],axis =1).to_csv(output_directory, index = None)

In [ ]:
# use a full grid over all parameters
model = DecisionTreeRegressor()
x = X_train
y = y_train
test = X_test
param_grid = {"max_depth": range(1,41,5),
              "max_leaf_nodes":range(600,1501,100)}

# run grid search
grid_search = GridSearchCV(model, param_grid=param_grid, cv=3, scoring="neg_mean_squared_error")
grid_search.fit(x, y)
pram = grid_search.best_params_
print(pram)
print(grid_search.best_score_)

{'max_depth': 16, 'max_leaf_nodes': 1300}
-1639785862.8504608


In [ ]:
#Defining parameters
#Setting a DTR model
model = DecisionTreeRegressor(**pram)
x = X_train
y = y_train
test = X_test

#Put in the function for prediction and outputs
model.fit(x,y)
rmse = math.sqrt(mean_squared_error(y, model.predict(x)))
print(rmse)
cross_val_score(model,x,y,cv=3, scoring="neg_mean_squared_error")

2780.4610898631977


array([-1.57457075e+09, -1.77543763e+09, -3.20657722e+09])

In [ ]:
#Save predictions
output_directory = r'/gdrive/My Drive/ColabNotebooks/Team Assignment/GridSearch_DT_Reg.csv'
predictions = model.predict(test)
ID = test["Id"]
predict=pd.DataFrame(predictions,columns=['SalePrice'])
pd.concat([ID, predict],axis =1).to_csv(output_directory, index = None)

In [ ]:
#=======================RFR=============================================
# use a full grid over all parameters
model = RandomForestRegressor()

param_grid = {"n_estimators": [50,100,150,200],
              "max_depth":range(20,41,10),
              "max_leaf_nodes":range(800,1600,100)}

# run grid search
grid_search = GridSearchCV(model, param_grid=param_grid, cv=3, scoring="neg_mean_squared_error")
grid_search.fit(x, y)
pram = grid_search.best_params_
print(pram)
print(grid_search.best_score_)

{'max_depth': 30, 'max_leaf_nodes': 1400, 'n_estimators': 150}
-893880992.204415


In [ ]:
#Setting a RFRmodel using best gridSearch Paramaters
model = RandomForestRegressor(**pram)
x = X_train
y = y_train
test = X_test

#Put in the function for prediction and outputs
model.fit(x,y)
rmse = math.sqrt(mean_squared_error(y, model.predict(x)))
print(rmse)
cross_val_score(model,x,y,cv=3, scoring="neg_mean_squared_error")

13381.991066962866


array([-7.72033155e+08, -1.10081642e+09, -1.21094604e+09])

In [ ]:
#Save predictions
output_directory = r'/gdrive/My Drive/ColabNotebooks/Team Assignment/RF_Reg.csv'
predictions = model.predict(test)
ID = test["Id"]
predict=pd.DataFrame(predictions,columns=['SalePrice'])
pd.concat([ID, predict],axis =1).to_csv(output_directory, index = None)

In [ ]:
#Gradient Boosting Regressor==============================================================================
# use a full grid over all parameters
model = GradientBoostingRegressor()

param_grid = {"n_estimators": [50,100,150,200],
              "max_features":["auto","log2","sqrt"],
              "learning_rate":[0.05,0.1,0.2]}

# run grid search
grid_search = GridSearchCV(model, param_grid=param_grid, cv=3, scoring="neg_mean_squared_error")
grid_search.fit(x, y)
pram = grid_search.best_params_
print(pram)
print(grid_search.best_score_)

{'learning_rate': 0.1, 'max_features': 'sqrt', 'n_estimators': 100}
-694042805.7110101


In [ ]:
#Setting a GBR model using best gridSearch Paramaters
model = GradientBoostingRegressor()
x = X_train
y = y_train
test = X_test

#Put in the function for prediction and outputs
model.fit(x,y)
rmse = math.sqrt(mean_squared_error(y, model.predict(x)))
print(rmse)
cross_val_score(model,x,y,cv=3, scoring="neg_mean_squared_error")

14522.55464790288


array([-5.73964259e+08, -8.44023014e+08, -6.63862101e+08])

In [ ]:
#Save predictions
output_directory = r'/gdrive/My Drive/ColabNotebooks/Team Assignment/GB_Reg.csv'
predictions = model.predict(test)
ID = test["Id"]
predict=pd.DataFrame(predictions,columns=['SalePrice'])
pd.concat([ID, predict],axis =1).to_csv(output_directory, index = None)

In [ ]:
#Multi layer perceptron ==============================================================================
# use a full grid over all parameters
model = MLPRegressor()

param_grid = {"max_iter": [1000,1250,1500],
              "solver":["lbfgs","sgd","adam"],
              "learning_rate":["constant","invscaling","adaptive"]}

# run grid search
grid_search = GridSearchCV(model, param_grid=param_grid, cv=3, scoring="neg_mean_squared_error")
grid_search.fit(x, y)
pram = grid_search.best_params_
print(pram)
print(grid_search.best_score_)

{'learning_rate': 'adaptive', 'max_iter': 1000, 'solver': 'lbfgs'}
-1511707708.5737324


In [ ]:
#Setting a MLP model using best gridSearch Paramaters
model = MLPRegressor()
x = X_train
y = y_train
test = X_test

#Put in the function for prediction and outputs
model.fit(x,y)
rmse = math.sqrt(mean_squared_error(y, model.predict(x)))
print(rmse)
cross_val_score(model,x,y,cv=3, scoring="neg_mean_squared_error")

43977.42841055921


array([-2.51249427e+09, -2.86338309e+09, -2.89338810e+09])

In [ ]:
#Save predictions
output_directory = r'/gdrive/My Drive/ColabNotebooks/Team Assignment/GridSearch_MLP.csv'
predictions = model.predict(test)
ID = test["Id"]
predict=pd.DataFrame(predictions,columns=['SalePrice'])
pd.concat([ID, predict],axis =1).to_csv(output_directory, index = None)

In [ ]:
#==========================Model Stacking

print("___________________________________________________________________________________________\nEnsemble Methods Predictions using GradientBoosting, RandomForest and Decision Tree Classifier\n")

# specify specific model to use to stack them together, you can pass the optimal solution of in the argument
models = [GradientBoostingRegressor() ,\
          RandomForestRegressor(max_depth=30, max_leaf_nodes=1400, n_estimators=150), \
          DecisionTreeRegressor() ]
      
S_Train, S_Test = stacking(models,                   
                           X_train, y_train, X_test,   
                           regression=True, 
                           mode='oof_pred_bag', 
                           needs_proba=False,
                           save_dir=None,
                           metric=mean_squared_error, 
                           n_folds=7, 
                           stratified=True,
                           shuffle=True,  
                           random_state=0,    
                           verbose=2)


___________________________________________________________________________________________
Ensemble Methods Predictions using GradientBoosting, RandomForest and Decision Tree Classifier

task:         [regression]
metric:       [mean_squared_error]
mode:         [oof_pred_bag]
n_models:     [3]

model  0:     [GradientBoostingRegressor]
    fold  0:  [564179302.33083892]
    fold  1:  [894216455.21147561]
    fold  2:  [555730065.05738556]
    fold  3:  [1218876651.79300904]
    fold  4:  [806349037.65491283]
    fold  5:  [462638574.28025395]
    fold  6:  [394827379.09468180]
    ----
    MEAN:     [699545352.20322251] + [269123851.77042353]
    FULL:     [699843174.85087991]

model  1:     [RandomForestRegressor]
    fold  0:  [673242259.07528555]
    fold  1:  [1282813393.45660663]
    fold  2:  [700774333.89826608]
    fold  3:  [1211901417.03859901]
    fold  4:  [850319694.88750696]
    fold  5:  [691374564.50219965]
    fold  6:  [485132903.34281570]
    ----
    MEAN:     [84

In [ ]:
#Setting a GBR model using Stacking dataset
model = GradientBoostingRegressor()
x = S_Train
y = y_train
test = S_Test

#Put in the function for prediction and outputs
model.fit(x,y)
rmse = math.sqrt(mean_squared_error(y, model.predict(x)))
print(rmse)
cross_val_score(model,x,y,cv=3, scoring="neg_mean_squared_error")

17888.394134950628


array([-6.78642655e+08, -1.02072245e+09, -7.81121958e+08])

In [ ]:
#Save predictions
output_directory = r'/gdrive/My Drive/ColabNotebooks/Team Assignment/GB_Stacking_Reg.csv'
predictions = model.predict(test)
ID = testData["Id"]
predict=pd.DataFrame(predictions,columns=['SalePrice'])
pd.concat([ID, predict],axis =1).to_csv(output_directory, index = None)

In [ ]:
#Setting a RFR model using Stacking dataset
model = RandomForestRegressor(max_depth=30, max_leaf_nodes=1400, n_estimators=150)
x = S_Train
y = y_train
test = S_Test

#Put in the function for prediction and outputs
model.fit(x,y)
rmse = math.sqrt(mean_squared_error(y, model.predict(x)))
print(rmse)
cross_val_score(model,x,y,cv=3, scoring="neg_mean_squared_error")

11117.912081821254


array([-6.14241707e+08, -1.10158923e+09, -7.35543320e+08])

In [ ]:
#Save predictions
output_directory = r'/gdrive/My Drive/ColabNotebooks/Team Assignment/GridSearch_RF_Stacking_Reg.csv'
predictions = model.predict(test)
ID = testData["Id"]
predict=pd.DataFrame(predictions,columns=['SalePrice'])
pd.concat([ID, predict],axis =1).to_csv(output_directory, index = None)

In [ ]:
#Setting a DT model using Stacking dataset
model = DecisionTreeRegressor()
x = S_Train
y = y_train
test = S_Test

#Put in the function for prediction and outputs
model.fit(x,y)
rmse = math.sqrt(mean_squared_error(y, model.predict(x)))
print(rmse)
cross_val_score(model,x,y,cv=3, scoring="neg_mean_squared_error")

0.0


array([-1.24830020e+09, -1.49967808e+09, -1.58173883e+09])

In [ ]:
#Save predictions
output_directory = r'/gdrive/My Drive/ColabNotebooks/Team Assignment/DT_Stacking_Reg.csv'
predictions = model.predict(test)
ID = testData["Id"]
predict=pd.DataFrame(predictions,columns=['SalePrice'])
pd.concat([ID, predict],axis =1).to_csv(output_directory, index = None)

In [ ]:
#Decision Tree Regressor ========================================================================
#CONSTRUCT DEFAULT DECISION TREE AND OBTAIN RESPECTIVE ACCURACY 
clf = DecisionTreeRegressor()
clf.fit(X_train, y_train)
predictions=clf.predict(X_test)

#Get prediction by using cross validation
yhat = cross_val_score(clf, X_train, y_train, score = '' cv=5,)
print(yhat)

In [ ]:
#Save predictions
ID = X_test["Id"]
predict=pd.DataFrame(predictions,columns=['SalePrice'])
pd.concat([ID, predict],axis =1).to_csv(r'/gdrive/My Drive/ColabNotebooks/Team Assignment/DT_Test.csv', index = None)

In [ ]:
#Random Forest Regressor==============================================================================
#=================================================================================================
rfc = RandomForestRegressor()
rfc.fit(X_train, y_train)
rfc_predict_Train=rfc.predict(X_train)

mean_squared_error(y_train,rfc_predict_Train)
print("RMSE (training) for Decision Tree:{0:10f}".format(mean_squared_error(y_train,rfc_predict_Train)))
rfc_predict_Test=rfc.predict(X_test)
mean_squared_error(y_test,rfc_predict_Test)
print("RMSE (Test Data) for Decision Tree:{0:10f}".format(mean_squared_error(y_test,rfc_predict_Test)))


RMSE (training) for Decision Tree:  0.000159
RMSE (Test Data) for Decision Tree:  0.001302


In [ ]:
#Save predictions
df_rfc=pd.DataFrame()
df_rfc['TARGET']=rfc_predict_Test
export_csv = df_rfc.to_csv(r'/gdrive/My Drive/ColabNotebooks/A4/RF_Test.csv')

In [ ]:
#Gradient Boosting Regressor================================================================================

abc =GradientBoostingRegressor()
abc.fit(X_train, y_train)
abc_predict_Train=abc.predict(X_train)

mean_squared_error(y_train,abc_predict_Train)
print("RMSE (training) for Decision Tree:{0:10f}".format(mean_squared_error(y_train,abc_predict_Train)))
abc_predict_Test=rfc.predict(X_test)
mean_squared_error(y_test,abc_predict_Test)
print("RMSE (Test Data) for Decision Tree:{0:10f}".format(mean_squared_error(y_test,abc_predict_Test)))




RMSE (training) for Decision Tree:  0.000073
RMSE (Test Data) for Decision Tree:  0.001302


In [ ]:
#Save predictions
df_abc=pd.DataFrame()
df_abc['TARGET']=abc_predict_Test
export_csv = df_abc.to_csv(r'/gdrive/My Drive/ColabNotebooks/A4/GB_Test.csv')

In [ ]:
#STACKING MODELS =====================================================================
print("___________________________________________________________________________________________\nEnsemble Methods Predictions using GradientBoosting, RandomForest and Decision Tree Classifier\n")

models = [ GradientBoostingRegressor(), RandomForestRegressor(), DecisionTreeRegressor() ]
      
S_Train, S_Test = stacking(models,                   
                           X_train, y_train, X_test,   
                           regression=True, 
     
                           mode='oof_pred_bag', 
       
                           needs_proba=False,
         
                           save_dir=None, 
                                        
                           n_folds=4, 
                                                    
                           verbose=2)



___________________________________________________________________________________________
Ensemble Methods Predictions using GradientBoosting, RandomForest and Decision Tree Classifier

task:         [regression]
metric:       [mean_absolute_error]
mode:         [oof_pred_bag]
n_models:     [3]

model  0:     [GradientBoostingRegressor]
    fold  0:  [0.02563111]
    fold  1:  [0.01814714]
    fold  2:  [0.01596021]
    fold  3:  [0.01780302]
    ----
    MEAN:     [0.01938537] + [0.00370061]
    FULL:     [0.01939205]

model  1:     [RandomForestRegressor]
    fold  0:  [0.02448682]
    fold  1:  [0.01943404]
    fold  2:  [0.01783374]
    fold  3:  [0.02041129]
    ----
    MEAN:     [0.02054147] + [0.00245667]
    FULL:     [0.02054526]

model  2:     [DecisionTreeRegressor]
    fold  0:  [0.03212766]
    fold  1:  [0.02425000]
    fold  2:  [0.02063636]
    fold  3:  [0.02388770]
    ----
    MEAN:     [0.02522543] + [0.00422615]
    FULL:     [0.02523333]



In [ ]:
#STACKING - CONTRUCT A GRADIENT BOOSTING MODEL==============================
model = GradientBoostingRegressor()
    
model = model.fit(S_Train, y_train)
y_pred_train = model.predict(S_Train)
y_pred_test = model.predict(S_Test)



In [ ]:
mean_squared_error(y_train,y_pred_train)
print("RMSE (training) for Decision Tree:{0:10f}".format(mean_squared_error(y_train,y_pred_train)))
mean_squared_error(y_test,y_pred_test)
print("RMSE (Test Data) for Decision Tree:{0:10f}".format(mean_squared_error(y_test,y_pred_test)))

RMSE (training) for Decision Tree:  0.000452
RMSE (Test Data) for Decision Tree:  0.000782


In [ ]:
#Save predictions
df_stacking=pd.DataFrame()
df_stacking['TARGET']=y_pred_test
export_csv = df_rfc.to_csv(r'/gdrive/My Drive/ColabNotebooks/A4/Stacking_Test.csv')